#!/usr/bin/env bash
# ============================================================================
#  brd.sh — Manage the Living BRD (docs/brd/requirements.yaml)
# ----------------------------------------------------------------------------
#  .helmforge/scripts/brd.sh init [product-name]   create docs/brd/ if absent
#  .helmforge/scripts/brd.sh next-id <DOMAIN> <FR|NFR>  print the next global ID (e.g. FR-AUTH-003)
#  .helmforge/scripts/brd.sh validate              check for duplicate IDs + required fields
#  .helmforge/scripts/brd.sh report                regenerate docs/brd/brd.md from the registry
# ============================================================================
set -uo pipefail
cd "$(dirname "$0")/../.." 2>/dev/null || true

if [ -t 1 ]; then G=$(printf '\033[32m'); R=$(printf '\033[31m'); Y=$(printf '\033[33m'); RST=$(printf '\033[0m'); else G=""; R=""; Y=""; RST=""; fi
ok(){ printf "%s✓%s %s\n" "$G" "$RST" "$*"; }
no(){ printf "%s✗%s %s\n" "$R" "$RST" "$*"; }
wn(){ printf "%s!%s %s\n" "$Y" "$RST" "$*"; }

BRD_DIR="docs/brd"
REG="$BRD_DIR/requirements.yaml"
DOC="$BRD_DIR/brd.md"

cmd="${1:-help}"

case "$cmd" in
  init)
    name="${2:-$(basename "$(pwd)")}"
    if [ -f "$REG" ]; then wn "$REG already exists — not overwriting."; exit 0; fi
    mkdir -p "$BRD_DIR"
    cat > "$REG" <<YAML
# Living BRD registry — source of truth for product requirements.
# Maintained by business-analyst (see .claude/skills/living-brd/SKILL.md).
# Append-as-you-go: features you build get recorded; do NOT back-fill legacy code.
product: $name
updated: $(date +%Y-%m-%d)
requirements: []
YAML
    ok "Created $REG"
    "$0" report >/dev/null 2>&1 || true
    ok "Created $DOC"
    ;;

  next-id)
    dom="${2:-}"; typ="${3:-}"
    [ -z "$dom" ] || [ -z "$typ" ] && { no "Usage: brd.sh next-id <DOMAIN> <FR|NFR>"; exit 1; }
    dom="$(printf '%s' "$dom" | tr '[:lower:]' '[:upper:]')"
    typ="$(printf '%s' "$typ" | tr '[:lower:]' '[:upper:]')"
    [ -f "$REG" ] || { echo "$typ-$dom-001"; exit 0; }
    max=$(grep -oE "id:[[:space:]]*$typ-$dom-[0-9]+" "$REG" 2>/dev/null | grep -oE '[0-9]+$' | sort -n | tail -1)
    next=$(( ${max:-0} + 1 ))
    printf "%s-%s-%03d\n" "$typ" "$dom" "$next"
    ;;

  validate)
    [ -f "$REG" ] || { wn "No $REG yet (run: brd.sh init)"; exit 0; }
    prob=0
    # duplicate IDs
    dups=$(grep -oE 'id:[[:space:]]*[A-Z]+-[A-Z0-9]+-[0-9]+' "$REG" | awk '{print $2}' | sort | uniq -d)
    if [ -n "$dups" ]; then no "Duplicate IDs:"; echo "$dups" | sed 's/^/    /'; prob=$((prob+1)); fi
    # per-record required fields (awk over blocks starting at '- id:')
    awk '
      /^[[:space:]]*-[[:space:]]*id:/ {
        if (have_id) check();
        delete f; have_id=1; id=$0; sub(/.*id:[[:space:]]*/,"",id); gsub(/[[:space:]]/,"",id); cur=id; next
      }
      have_id && /^[[:space:]]+[a-z_]+:/ { k=$0; sub(/:.*/,"",k); gsub(/[[:space:]]/,"",k); f[k]=1 }
      END { if (have_id) check() }
      function check(){
        for (need_i in REQ) {}
        split("type domain status statement", req, " ")
        for (i in req) if (!(req[i] in f)) { print "    " cur ": missing field " req[i]; bad++ }
        if (f["status"]=="" ) {}
      }
    ' "$REG" | { out=$(cat); [ -n "$out" ] && { no "Missing fields:"; echo "$out"; prob=$((prob+1)); } || true; }
    # shipped must have acceptance + pr (heuristic: warn only)
    if [ "$prob" = 0 ]; then ok "BRD valid: no duplicate IDs, all required fields present."; else no "$prob problem group(s)."; exit 2; fi
    ;;

  report)
    [ -f "$REG" ] || { wn "No $REG yet"; exit 0; }
    mkdir -p "$BRD_DIR"
    prod=$(grep -E '^product:' "$REG" | head -1 | sed 's/^product:[[:space:]]*//')
    {
      echo "# Business Requirements — $prod"
      echo ""
      echo "> Source of truth: \`docs/brd/requirements.yaml\`. This file is GENERATED by \`scripts/brd.sh report\` — do not hand-edit. Updated $(date +%Y-%m-%d)."
      echo ""
      # counts by status
      echo "## Status summary"
      echo ""
      for st in proposed planned in-progress shipped deprecated; do
        n=$(grep -cE "status:[[:space:]]*$st([[:space:]]|$)" "$REG" 2>/dev/null); n=${n:-0}
        [ "$n" -gt 0 ] 2>/dev/null && echo "- $st: $n"
      done
      echo ""
      echo "## Requirements"
      echo ""
      echo "| ID | Type | Status | Priority | Statement | Ticket | PR | Acceptance |"
      echo "|----|------|--------|----------|-----------|--------|----|------------|"
      # parse blocks
      awk '
        function flush(){
          if (id!="") printf "| %s | %s | %s | %s | %s | %s | %s | %s |\n",
            id, type, status, prio, stmt, ticket, pr, acc
          id="";type="";status="";prio="";stmt="";ticket="";pr="";acc=""
        }
        /^[[:space:]]*-[[:space:]]*id:/ { flush(); id=$0; sub(/.*id:[[:space:]]*/,"",id); gsub(/[[:space:]]/,"",id); next }
        /^[[:space:]]+type:/    { type=val($0) }
        /^[[:space:]]+status:/  { status=val($0) }
        /^[[:space:]]+priority:/{ prio=val($0) }
        /^[[:space:]]+statement:/{ stmt=val($0); gsub(/^"|"$/,"",stmt) }
        /^[[:space:]]+ticket:/  { ticket=val($0) }
        /^[[:space:]]+pr:/      { pr=val($0); gsub(/"/,"",pr) }
        /^[[:space:]]+acceptance:/{ acc=val($0) }
        END { flush() }
        function val(line){ sub(/^[^:]*:[[:space:]]*/,"",line); gsub(/[[:space:]]*#.*$/,"",line); return line }
      ' "$REG"
      echo ""
      echo "## Traceability"
      echo ""
      echo "Each requirement above links to its acceptance scenario, ticket, and PR. Filter by domain via the ID prefix (e.g. all \`*-AUTH-*\`)."
    } > "$DOC"
    ok "Regenerated $DOC from $REG"
    ;;

  *)
    echo "brd.sh — Living BRD"
    echo "  init [name]            create docs/brd/"
    echo "  next-id <DOMAIN> <FR|NFR>"
    echo "  validate"
    echo "  report"
    ;;
esac
